// eslint-disable-next-line no-unused-vars
const categoryList = [
  { code: 'all', name: 'Todas' },
  { code: 'agents', name: 'Agentes' },
  { code: 'art', name: 'Arte' },
  { code: 'audio', name: 'Áudio' },
  { code: 'book', name: 'Livro' },
  { code: 'blogging', name: 'Blogging' },
  { code: 'branding', name: 'Marca' },
  { code: 'business', name: 'Negócios' },
  { code: 'coding', name: 'Programação' },
  { code: 'copywriting', name: 'Copywriting' },
  { code: 'creative', name: 'Criativo' },
  { code: 'data', name: 'Dados' },
  { code: 'design', name: 'Design' },
  { code: 'education', name: 'Educação' },
  { code: 'email', name: 'Email' },
  { code: 'extraction', name: 'Extração' },
  { code: 'fantasy', name: 'Fantasia' },
  { code: 'food', name: 'Comida' },
  { code: 'games', name: 'Jogos' },
  { code: 'general', name: 'Geral' },
  { code: 'health_&_wellness', name: 'Saúde & Bem-estar' },
  { code: 'ideas', name: 'Ideias' },
  { code: 'image_generation', name: 'Geração de Imagens' },
  { code: 'jailbreak', name: 'Jailbreak' },
  { code: 'learning', name: 'Aprendizado' },
  { code: 'legal', name: 'Jurídico' },
  { code: 'literature', name: 'Literatura' },
  { code: 'marketing', name: 'Marketing' },
  { code: 'movies', name: 'Filmes' },
  { code: 'news', name: 'Notícias' },
  { code: 'personal', name: 'Pessoal' },
  { code: 'photography', name: 'Fotografia' },
  { code: 'productivity', name: 'Produtividade' },
  { code: 'real_estate', name: 'Imóveis' },
  { code: 'relationship', name: 'Relacionamento' },
  { code: 'research', name: 'Pesquisa' },
  { code: 'science', name: 'Ciência' },
  { code: 'saas', name: 'SaaS' },
  { code: 'seo', name: 'SEO' },
  { code: 'social_media', name: 'Mídias Sociais' },
  { code: 'summarization', name: 'Resumo' },
  { code: 'tagging', name: 'Etiquetagem' },
  { code: 'tones', name: 'Tons' },
  { code: 'translation', name: 'Tradução' },
  { code: 'videos', name: 'Vídeos' },
];
